name: Lint

on:
  pull_request:
    branches:
      - dev
      - master

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  lint:
    name: StyLua
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Check formatting
        uses: JohnnyMorganz/stylua-action@v5
        with:
          token: ${{ github.token }}
          version: 2.5.2
          args: --check lua/ plugin/ tests/
